# config.yaml
# Конфигурация сети Solana
network:
  cluster_url: "https://api.devnet.solana.com"  # Devnet для тестирования
  # cluster_url: "https://api.mainnet-beta.solana.com"  # Mainnet
  commitment: "confirmed"  # Уровень подтверждения транзакций: processed, confirmed, finalized

# Кошельки источники с приватными ключами (для подписи транзакций)
# Эти тестовые ключи сгенерированы только для примера - НЕ ИСПОЛЬЗУЙТЕ ИХ для реальных средств!
# Для генерации своих ключей используйте solana-keygen
source_wallets:
  - secret_key: "[174,47,154,16,202,193,206,113,199,190,53,133,169,175,31,56,222,53,138,189,224,216,117,173,10,149,53,45,73,251,237,124]"
    amount: 0.001  # Количество SOL для отправки (в SOL)
  - secret_key: "[202,171,192,129,150,189,204,241,134,50,133,98,110,254,185,58,36,27,33,242,124,137,182,72,89,20,99,221,5,85,197,97]"
    amount: 0.001
  - secret_key: "[231,159,52,64,98,128,22,246,24,243,165,214,145,79,5,60,237,68,40,59,46,12,144,141,135,83,156,240,226,119,233,127]"
    amount: 0.001

# Целевые кошельки для получения SOL
destination_wallets:
  - "9iD1LM1wQ7zPhZ1LnYUyPBgvKW3d3TvDTBR3ZU4HHLhb"
  - "JBZqsAU2ajShkCHFKhyG6Q9QmfaJapNozXE7D751KoBH" 
  - "Ao2ZZJ58MN2zQyRxG8oGNPzuQ4wL3GQF49GdUWBnrVUt"

# Настройки транзакций
transaction_options:
  # Сколько времени ждать подтверждения транзакций (в секундах)
  confirmation_timeout: 60
  # Таймаут между проверками статуса (в миллисекундах)
  status_check_interval: 2000
  # Максимальное количество попыток для проверки статуса транзакций
  max_retries: 10
  # Учитывать комиссию за транзакцию (если true, сумма перевода будет снижена на величину комиссии)
  adjust_for_fee: true